### ISSUE TITLE
Property for text hiding

### ISSUE THREAD

**Issue by VaclovasV** [paulgabronis/Easy-Sprites#12]
I think it would be nice, to have additional property, for hiding text in the icon.
For example, you have text in icon, that shouldn't be displayed:
$hide-text:true, would add text-indent, overflow hidden css properties, to hide text inside icon.

**Comment by paulgabronis** [comment]
Testinam

**Comment by paulgabronis** [comment]
test

**Comment by paulgabronis** [comment]
fixed
